### ISSUE TITLE
Scrollbar stays active after clicking on it

### ISSUE THREAD

**Issue by alalpod** [FRSOURCE/light-scrollbar#196]
Hi Szymon, :wave: Phrase sends regards. We ran into minor bug with scrollbar.

**Describe the bug**
When user clicks on scrollbar ( or grab it and scroll with it ) and then release mouse, scrollbar stays active, so when user tries to select text in different element the scroll follows mouse move. Video should describe it better - https://share.getcloudapp.com/4gu4drPW

**To Reproduce**
1. Go to the example page https://www.frsource.org/light-scrollbar/examples/default.html
2. Click on scrollbar once ( or grab and scroll with it )
3. Try to select text in sidebar

**Expected behavior**
Content in attached container is scrolled

**Screenshots**
Content in attached container is no affected by mouse interactions outside of container

**Please complete the following information:**
 - Version - latest - 1.4.14
 - Browser - Chrome

**Additional context**
I tried to fix it by changing line 396 from
```javascript
outerElement.addEventListener("click", clickHandler);
```
to
```javascript
outerElement.addEventListener("mousedown", clickHandler);
outerElement.addEventListener("mouseup", mouseUpHandler);
```
I hoped it would help as `click` event fires after `mouseup`, but it helped only partially. For some reason y-axis scrollbar was more responsive to this change, but x-axis didn't change it behavior at all, especially when I tried to select text under the attached element ( before mount, after mount sections )

**Comment by Szymon-dziewonski** [comment]
@alalpod Hey Sasa :), Thanks for reaching out, I will definitely look into this issue and get back to you shortly :)

**Comment by Szymon-dziewonski** [comment]
Hey @alalpod , here's https://github.com/FRSOURCE/light-scrollbar/pull/200 fix for this issue, could you please check it out if this resolves issue ?

**Comment by alalpod** [comment]
@Szymon-dziewonski Hi, yeah, works great, thanks a lot!

**Comment by Szymon-dziewonski** [comment]
@alalpod great, thank Im merging it and soon should be available on npm :)

**Comment by Szymon-dziewonski** [comment]
@alalpod version 1.4.17 has been released :) https://www.npmjs.com/package/@frsource/light-scrollbar/v/1.4.17
