### ISSUE TITLE
Wrong scrollbar position with a lot of content

### ISSUE THREAD

**Issue by alalpod** [FRSOURCE/light-scrollbar#242]
Hi Szymon, me again :wave: 

**Describe the bug**
Scrollbar calculates `--ls-bar-y-top` variable wrong when it has a lot of content.

**To Reproduce**
1. In docs, click on `Add Dynamically item` button at least 70 times ( a bit masochistic approach :smile:  ) or just add v-for with at least 100 elements in `scrollbarTemplate.vue` - `<span v-for="it in 100" :key="it">Some Content<br/></span>`
2. Look at both examples - inner and outside
3. Scrollbar is positioned higher than container

**Expected behavior**
Scrollbar is positioned at container top and doesn't go higher

**Screenshots**
![Screenshot from 2023-03-21 14-44-34](https://user-images.githubusercontent.com/11444398/226627495-457e2790-8528-4800-901e-8a2ecf003fae.png)
![Screenshot from 2023-03-21 14-44-22](https://user-images.githubusercontent.com/11444398/226627501-df9ed848-c996-4e9f-ba87-ce4c9b347946.png)

**Please complete the following information:**
 - Happens in Ubuntu and Mac ( probably Win too )
 - All browsers

**Comment by alalpod** [comment]
Hi @Szymon-dziewonski , would you have time to check this issue?

**Comment by Szymon-dziewonski** [comment]
@alalpod hey sorry, rough time, will try to look into it this weekend

**Comment by Szymon-dziewonski** [comment]
Hey @alalpod once again sorry for long resolving issue. Here's fix for it https://github.com/FRSOURCE/light-scrollbar/pull/269 with also additional button to add +100 dynamic items

**Comment by Szymon-dziewonski** [comment]
@alalpod I just merged fix, please check it out, closing issue ticket for now, but please let me know if issue still occurs on your side.
Will be released in version `1.4.53`

**Comment by alalpod** [comment]
@Szymon-dziewonski thanks a lot! Works perfect :partying_face:
